# 标记是从哪个工程启动
#start:
#  project: spring-boot-training
#  security-filter:
#    enabled: false

server:
  port: 8080
#  session:
#    timeout: 30m         # Session timeout in seconds.

spring:
  datasource: # 数据源配置
    druid: 
      base:  # 基础数据源配置
        url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
        username: BISS
        password: BISS
        initial-size: 5
        max-active: 20
        max-wait: 10000

    


